import type { Metadata } from 'next'
import './globals.css'

export const metadata: Metadata = {
  title: 'Expanzo react test',
  description: 'Generated by create next app',
  icons: {
    icon: '/logo.svg'
  }
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  )
}
